<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of Parts
 *
 * @author Jake
 */
class Partsdata extends CI_Model {

    var $data = array(
        array('id' => '1',
            'name' => 'part A-1',
            'partCode' => 'A1',
            'CA' => '000001',
            'builtAt' => 'Strawberry',
            'builtTime' => 'Jan-01-2017',
            'aquiredTime' => 'Jan-30-2017',
            'part' => 'head',
            'fileName' => 'a1.jpeg',
            'href' => '/parts/1'),
        array('id' => '2',
            'name' => 'part A-2',
            'partCode' => 'A2',
            'CA' => '000002',
            'builtAt' => 'Strawberry',
            'builtTime' => 'Jan-01-2017',
            'aquiredTime' => 'Jan-30-2017',
            'part' => 'head',
            'fileName' => 'a2.jpeg',
            'href' => '/parts/2'),
        array('id' => '3',
            'name' => 'part A-3',
            'partCode' => 'A3',
            'CA' => '000003',
            'builtAt' => 'Strawberry',
            'builtTime' => 'Jan-01-2017',
            'aquiredTime' => 'Jan-30-2017',
            'part' => 'head',
            'fileName' => 'a3.jpeg',
            'href' => '/parts/3'),
        array('id' => '4',
            'name' => 'part B-1',
            'partCode' => 'B1',
            'CA' => '000004',
            'builtAt' => 'Strawberry',
            'builtTime' => 'Jan-01-2017',
            'aquiredTime' => 'Jan-30-2017',
            'part' => 'head',
            'fileName' => 'b1.jpeg',
            'href' => '/parts/4'),
        array('id' => '5',
            'name' => 'part B-2',
            'partCode' => 'B2',
            'CA' => '000005',
            'builtAt' => 'Strawberry',
            'builtTime' => 'Jan-01-2017',
            'aquiredTime' => 'Jan-30-2017',
            'part' => 'head',
            'fileName' => 'b2.jpeg',
            'href' => '/parts/5'),
        array('id' => '6',
            'name' => 'part B-3',
            'partCode' => 'B3',
            'CA' => '000006',
            'builtAt' => 'Strawberry',
            'builtTime' => 'Jan-01-2017',
            'aquiredTime' => 'Jan-30-2017',
            'part' => 'head',
            'fileName' => 'b3.jpeg',
            'href' => '/parts/6'),
        array('id' => '7',
            'name' => 'part C-1',
            'partCode' => 'C1',
            'CA' => '000007',
            'builtAt' => 'Strawberry',
            'builtTime' => 'Jan-01-2017',
            'aquiredTime' => 'Jan-30-2017',
            'part' => 'head',
            'fileName' => 'c1.jpeg',
            'href' => '/parts/7'),
        array('id' => '8',
            'name' => 'part C-2',
            'partCode' => 'C2',
            'CA' => '000008',
            'builtAt' => 'Strawberry',
            'builtTime' => 'Jan-01-2017',
            'aquiredTime' => 'Jan-30-2017',
            'part' => 'head',
            'fileName' => 'c2.jpeg',
            'href' => '/parts/8'),
        array('id' => '9',
            'name' => 'part C-3',
            'partCode' => 'C3',
            'CA' => '000009',
            'builtAt' => 'Strawberry',
            'builtTime' => 'Jan-01-2017',
            'aquiredTime' => 'Jan-30-2017',
            'part' => 'head',
            'fileName' => 'c3.jpeg',
            'href' => '/parts/9'),
        array('id' => '10',
            'name' => 'part M-1',
            'partCode' => 'M1',
            'CA' => '000010',
            'builtAt' => 'Strawberry',
            'builtTime' => 'Jan-01-2017',
            'aquiredTime' => 'Jan-30-2017',
            'part' => 'head',
            'fileName' => 'm1.jpeg',
            'href' => '/parts/10'),
        array('id' => '11',
            'name' => 'part M-2',
            'partCode' => 'M2',
            'CA' => '000011',
            'builtAt' => 'Strawberry',
            'builtTime' => 'Jan-01-2017',
            'aquiredTime' => 'Jan-30-2017',
            'part' => 'head',
            'fileName' => 'm2.jpeg',
            'href' => '/parts/11'),
        array('id' => '12',
            'name' => 'part M-3',
            'partCode' => 'M3',
            'CA' => '000012',
            'builtAt' => 'Strawberry',
            'builtTime' => 'Jan-01-2017',
            'aquiredTime' => 'Jan-30-2017',
            'part' => 'head',
            'fileName' => 'm3.jpeg',
            'href' => '/parts/12'),
        array('id' => '13',
            'name' => 'part R-1',
            'partCode' => 'R1',
            'CA' => '000013',
            'builtAt' => 'Strawberry',
            'builtTime' => 'Jan-01-2017',
            'aquiredTime' => 'Jan-30-2017',
            'part' => 'head',
            'fileName' => 'r1.jpeg',
            'href' => '/parts/13'),
        array('id' => '14',
            'name' => 'part R-2',
            'partCode' => 'R2',
            'CA' => '000014',
            'builtAt' => 'Strawberry',
            'builtTime' => 'Jan-01-2017',
            'aquiredTime' => 'Jan-30-2017',
            'part' => 'head',
            'fileName' => 'r2.jpeg',
            'href' => '/parts/14'),
        array('id' => '15',
            'name' => 'part R-3',
            'partCode' => 'R3',
            'CA' => '000015',
            'builtAt' => 'Strawberry',
            'builtTime' => 'Jan-01-2017',
            'aquiredTime' => 'Jan-30-2017',
            'part' => 'head',
            'fileName' => 'r3.jpeg',
            'href' => '/parts/15'),
        array('id' => '16',
            'name' => 'part W-1',
            'partCode' => 'W1',
            'CA' => '000016',
            'builtAt' => 'Strawberry',
            'builtTime' => 'Jan-01-2017',
            'aquiredTime' => 'Jan-30-2017',
            'part' => 'head',
            'fileName' => 'w1.jpeg',
            'href' => '/parts/16'),
        array('id' => '17',
            'name' => 'part W-2',
            'partCode' => 'W2',
            'CA' => '000017',
            'builtAt' => 'Strawberry',
            'builtTime' => 'Jan-01-2017',
            'aquiredTime' => 'Jan-30-2017',
            'part' => 'head',
            'fileName' => 'w2.jpeg',
            'href' => '/parts/17'),
        array('id' => '18',
            'name' => 'part W-3',
            'partCode' => 'W3',
            'CA' => '000018',
            'builtAt' => 'Strawberry',
            'builtTime' => 'Jan-01-2017',
            'aquiredTime' => 'Jan-30-2017',
            'part' => 'head',
            'fileName' => 'w3.jpeg',
            'href' => '/parts/18'),
    );

    // Constructor    
    public function __construct() {
        parent::__construct();
    }

    // retrieve all of the parts
    public function getAllParts() {
        return $this->data;
    }

    // retrieve a single part
    public function getPart($which) {
        // iterate over the data until we find the one we want
        foreach ($this->data as $record) {
            if ($record['id'] == $which) {
                return $record;
            }
        }
        return null;
    }

}
